### ISSUE TITLE
Data der vises i "load data" fanen

### ISSUE THREAD

**Issue by websejler** [websejler/loebsindeling#12]
![image](https://user-images.githubusercontent.com/124284918/222252907-2eb3fd0c-82a5-4bb4-8a14-1cabb23d9e4b.png)

**Comment by juliusstr** [comment]
Note:
Tilføj til wiki

**Comment by websejler** [comment]
Det vil være godt hvis data kan vises i et "grid" - det gør det mere overskueligt

**Comment by juliusstr** [comment]
data vises nu som 

> ![image](https://user-images.githubusercontent.com/124284918/222252907-2eb3fd0c-82a5-4bb4-8a14-1cabb23d9e4b.png)

mangler at sætte det i et grid

**Comment by juliusstr** [comment]
#26 lukker da done
