### ISSUE TITLE
Import af excelfil

### ISSUE THREAD

**Issue by websejler** [websejler/loebsindeling#13]
Pt importerer vi csv fil (med komma) - dvs. der skal konverteres fra excel til csv før import. 
Er det muligt at lave det således at man kan importere fra en excel-fil

**Comment by juliusstr** [comment]
Efter en hurtig google søgning. så er svart ja det kan vi sagtens.

**Comment by juliusstr** [comment]
se evt:
[https://coderwall.com/p/app3ya/read-excel-file-in-c](https://coderwall.com/p/app3ya/read-excel-file-in-c)

**Comment by websejler** [comment]
Excel-fil og/eller semikolonsepareret-fil vil være godt
