### ISSUE TITLE
DH CDL

### ISSUE THREAD

**Issue by juliusstr** [websejler/loebsindeling#14]
hastigheden = 2.65 * kvadr (lwl)

ta6

DHWL = loa- oa -of

**Comment by websejler** [comment]
Den beregnede DH CDL skal vises i output (evt. også i faner med output)

**Comment by juliusstr** [comment]
@websejler 
Tænker dette skal være en sorterings algoritme.
link til: [ORC CDL](https://orc.org/news/2014/CDL%20Explanation.pdf)
Deres UP12 er vores TAU6.
Deres IMS L er vores DHWL.
Hvor DHWL = LOA-OA-OF.
Kommentarer?

sender også en mail til KWE
