### ISSUE TITLE
Opdeling af både med/uden flyvesejl

### ISSUE THREAD

**Issue by websejler** [websejler/loebsindeling#17]
Som test - kan der laves en sortering hvor både sorteres på "flyvesejl", dvs. 
- Kun spiler - SL er registreret, SLU=0
- Kun asymmetrisk spiler - SLU er registreret, SL=0 
- Både symmetrisk og asymmetrisk spiler - SL og SLU er registreret
- Ingen flyvesejl - SL=0 og SLU=0

**Comment by juliusstr** [comment]
@websejler kan du komme med et eksempel?
Jeg kan ikke lige gennemskue hvordan bådens flyvesejl skal påvirke deres soterings tal.
eller mener du at vi der skal grupperes efter det så både med spiler ikke sejler mod gennaker ud over soterings tallet.

**Comment by websejler** [comment]
Hej Julius

Det er mest for at kunne skelne, evt. opdele, så både med spiler ikke sejler mod både uden spiler eller mod både med asymmetrisk spiler.
Nedenfor et eksempel hvor man kan se hvilken form for flyvesejl den pågældende båd er registreret med.
”tom” = ingen flyvesejl
S = spiler
S/A = symmetrisk og asymmetrisk spiler
A = asymmetrisk spiler

/Mikael


***@***.***

Fra: juliusstr ***@***.***>
Sendt: 23. marts 2023 08:43
Til: websejler/loebsindeling ***@***.***>
Cc: Mikael Jeremiassen ***@***.***>; Mention ***@***.***>
Emne: Re: [websejler/loebsindeling] Opdeling af både med/uden flyvesejl (Issue #17)


@websejler<https://github.com/websejler> kan du komme med et eksempel?
Jeg kan ikke lige gennemskue hvordan bådens flyvesejl skal påvirke deres soterings tal.
eller mener du at vi der skal grupperes efter det så både med spiler ikke sejler mod gennaker ud over soterings tallet.

**Comment by juliusstr** [comment]
![image001](https://user-images.githubusercontent.com/23530650/227139024-96cebbae-9ab6-47c6-9ab6-1a88d6b6a3a4.png)

**Comment by juliusstr** [comment]
@websejler
super så det skal ikke påvirke soterings tallet, men det skal være muligt at vælge om både med forskelige flyve sejl skal sejle for sig selv under gruppering

**Comment by websejler** [comment]
ja

Fra: juliusstr ***@***.***>
Sendt: 23. marts 2023 09:03
Til: websejler/loebsindeling ***@***.***>
Cc: Mikael Jeremiassen ***@***.***>; Mention ***@***.***>
Emne: Re: [websejler/loebsindeling] Opdeling af både med/uden flyvesejl (Issue #17)


@websejler<https://github.com/websejler>
super så det skal ikke påvirke soterings tallet, men det skal være muligt at vælge om både med forskelige flyve sejl skal sejle for sig selv under gruppering

**Comment by juliusstr** [comment]
tilføjer dette som en option til JST-grouping

**Comment by juliusstr** [comment]
Har skiftet mening. dette blvier sin egen grupperings metode. Den kommer til at hedde "Flyve Grupper"
