### ISSUE TITLE
Fanen sorter både fil skal indholde mere data.

### ISSUE THREAD

**Issue by websejler** [websejler/loebsindeling#29]
Fanen sorter både fil skal indholde mere data - og må meget gerne være i grid
Skal indeholde de samme data som i inputfane til at identificere båd - og så er det muligt at der er nogle TA-værdier der også skal med.

**Comment by juliusstr** [comment]
[evt](https://github.com/websejler/loebsindeling/issues/28#issuecomment-1486639573)
