### ISSUE TITLE
Graf gruppering

### ISSUE THREAD

**Issue by Anlc1992** [websejler/loebsindeling#45]
En visuel repræsentation af grupperinger på en graf.
Fx. Sorterings score op af Y-aksen og LOA ud af X-aksen. Bådene kan være repræsenteret af et punkt hvor navnet vises når markøren svæver over punktet.
Det skal være muligt at selv vælge hvad der skal være på de X-aksen.
Der skal kunne indsættes linjer/gruppe-skiller ved at klikke/vælge punkter på Y-aksen og de skal være modificer bare.

**Comment by juliusstr** [comment]
@websejler
Hvad siger du til denne metode at indele grupper/løb på?

**Comment by websejler** [comment]
Spændende

Fra: juliusstr ***@***.***>
Sendt: 27. april 2023 10:11
Til: websejler/loebsindeling ***@***.***>
Cc: Mikael Jeremiassen ***@***.***>; Mention ***@***.***>
Emne: Re: [websejler/loebsindeling] Graf gruppering (Issue #45)


@websejler<https://github.com/websejler>
Hvad siger du til denne metode at indele grupper/løb på?

**Comment by juliusstr** [comment]
Man bør kunne vælge hvilke data man vi se på de 2 akser.

standart kan evt være "score" og "L"(LOA-OF-OA)
