### ISSUE TITLE
Når JST gruppering anvendes forsøger jeg at lave 26 grupper, men kun 16 accepteres

### ISSUE THREAD

**Issue by websejler** [websejler/loebsindeling#49]

**Comment by juliusstr** [comment]
Har tested på spangsberCup2022udtræk hvor den skulle lave 26 løb man kun laver 22. tænker det samem problem med anden data.
kigger videre på det.

@websejler  hvis du kan sende data eller ligge det her vill det hjælpe en del til at løse problemet.

**Comment by juliusstr** [comment]
Rettelse. 
Den virker som tiltænkt. Men giver måske nogle lidt andre resultator end forventet.
Dette sker når der er mange både og der kommer mellemrum i data se billede eneden for:
![image](https://github.com/websejler/loebsindeling/assets/23530650/19bdfba7-6ccb-45c5-acae-26870e283c77)
Da der er stor spredeler på data men grupperne ligger i intervallet [1;10[ og så vider der op af, vil der kun blive genereret 5 løb.

Er det svar @websejler

**Comment by juliusstr** [comment]
Der skal laves en anden algoritme hvis der altid skal laves x løb hvis der er det der specificeres.
