### ISSUE TITLE
Velkommen til fane

### ISSUE THREAD

**Issue by wedersoe** [websejler/loebsindeling#68]
Vi bør nok have en forklarende tekst der popper op når man åbner programmet.
Jeg kan godt skrive teksten

**Comment by juliusstr** [comment]
Skal bruge noget tekst her til
@wedersoe skrev du det?

**Comment by juliusstr** [comment]
![image](https://github.com/websejler/loebsindeling/assets/23530650/7b9f1c85-5055-4d3b-a595-d047330be576)
Det er pt sådan ud

**Comment by juliusstr** [comment]
Velkommen til Dansk Sejlunion, Teknisk Udvalg - testmiljø for Løbsinddeling
